config/routes.rb
Rails.application.routes.draw do
  root 'blogs#index'

  namespace :admin do
    resources :posts do
      collection do
        post :preview
      end
      resources :comments
    end
    resources :sessions

    get 'dashboard/index'

  end

  resources :blogs do
    resources :comments
    resource :like,  module: :blogs
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  validates_presence_of :post_id

  validates :name, presence: true
  validates :email, presence: true
  validates :content, presence: true


end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :post
  validates_presence_of :post_id
end

app/models/post.rb
class Post < ApplicationRecord

  has_many :comments

  validates :title, presence: {message: "title can't be blank"}
  validates :content, uniqueness: {message: "the content exist"}

   has_many :posts_tags, class_name: 'PostsTags'
   has_many :tags, through: :posts_tags

  #  def visited
  #   self.visited_count += 1
  #   self.save
  #   self.visited_count
  # end
end

app/models/posts_tags.rb
class PostsTags < ApplicationRecord
  self.table_name = 'posts_tags'

  validates_uniqueness_of :post_id, scope: [:tag_id]

  belongs_to :post
  belongs_to :tag
end

app/models/tag.rb
class Tag < ApplicationRecord
  validates :title, uniqueness: {message: "tag 已经存在"}

  has_many :posts_tags, class_name: "PostsTags"
  has_many :posts, through: :posts_tags
end

app/controllers/admin/comments_controller.rb
class Admin::CommentsController < ApplicationController
  layout 'admin'
  before_action :authericate_user!

  before_action do
    @post = Post.find( params[:post_id] )
  end

  def index
    @comments = @post.comments.order(created_at: :desc)
  end

  def destroy
    comment = @post.comments.find(params[:id])
    if comment.destroy
      flash[:notice] = '删除评论成功'
      redirect_to admin_post_comments_path(@post)
    else
      flash[:alert] = '删除失败'
      redirect_to admin_post_comments_path(@post)
    end
  end
end

app/controllers/admin/dashboard_controller.rb
class Admin::DashboardController < ApplicationController
  layout 'admin'
  before_action :authericate_user!

  def index
    @posts_count = Post.all.size
    @comments_count = Comment.all.size
    # @visited_count = Post.all.inject(0) { |res, p| res + p.visited_count }
  end
end

app/controllers/admin/posts_controller.rb
class Admin::PostsController < ApplicationController
  layout 'admin'
  before_action :authericate_user!

  def new
    @post = Post.new
  end

  def edit
    @post = Post.find( params[:id] )
    render :new
  end

  def destroy
    @post = Post.find( params[:id] )
    if @post.destroy
      flash[:notice] = '删除博客成功'
      redirect_to admin_posts_path
    else
      flash[:error] = '删除博客失败'
      redirect_to admin_posts_path
    end
  end

  def index
    @posts = Post.order(created_at: :desc).page(params[:page]).per(5)
  end

  def create
     @post = Post.new(post_attrs)

    if @post.save

      init_tags

      flash[:notice] = '创建博客成功'
      redirect_to admin_posts_path
    else
      flash.now[:error] = '创建失败'
      render :new
    end
  end

  def update
    @post = Post.find( params[:id] )
    @post.attributes = post_attrs

    if @post.save
      @post.tags.destroy_all
      init_tags
      flash[:notice] = '更新博客成功'
      redirect_to admin_posts_path
    else
      flash[:notice] = '更新博客失败'
      render :new
    end
  end

  def preview
    content = params[:content]
    require 'my_markdown'
    render plain: MyMarkdown.to_md(content)
  end

  private
  def post_attrs
    params.require(:post).permit(:title, :content)
  end

  def init_tags
    params[:tags].split(',').each do |tag|
      one_tag = Tag.find_by(title: tag)
      one_tag = Tag.new(title: tag) unless one_tag

      @post.tags << one_tag
    end
  end
end

app/controllers/admin/sessions_controller.rb
class Admin::SessionsController < ApplicationController
  # layout 'layouts/admin'

  def new
  end

  def create
    if ENV['ADMIN_USER'].blank?
      flash[:notice] = "Please put your username"
      render :new
    elsif ENV['ADMIN_USER'] != params[:username]
      flash[:notice] = "Wrong username"
      render :new
    elsif ENV['ADMIN_PASSWORD'] != params[:password]
      flash[:notice] = "Wrong password"
      render :new
    else
      flash[:notice] = "OK, You got it."
      session[:login_info] = true
      redirect_to admin_dashboard_index_path
    end
  end

  def destroy
    session[:login_info] = nil
    redirect_to new_admin_session_path
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  helper_method :format_time, :format_date

  helper_method :admin_username

  def format_time(time)
    time.strftime("%Y-%m-%d %H:%M")
  end

  def format_date(time)
    time.strftime("%Y.%m.%d")
  end

  before_action do
    @latst_posts = Post.order(created_at: 'desc').limit(8)
  end

  protected
  def authericate_user!
    if ! session[:login_info]
      flash[:error] = '请先登录后台管理'
      cookies[:urlback] = request.original_url
      redirect_to new_admin_session_path
    end
  end

  def admin_username
    session[:login_info] && ENV['ADMIN_USER']
  end
end

app/controllers/blogs/likes_controller.rb
class Blogs::likesController < ApplicationController
   before_action :set_blog

  def create
    @blog.likes.first_or_create

    respond_to do |format|
      format.html {redirect_to @blog}
      format.js
    end
  end

  def destroy
    @blog.likes.destroy_all

    respond_to do |format|
      format.html { redirect_to @blog}
      format.js
    end
  end

  private
    def set_blog
      @blog = Post.find(params[:blog_id])
    end
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController

  def index
    @q = Post.search(params[:q])
    @posts = @q.result(distinct: true).order(created_at: :desc).page(params[:page]).per(5)
  end

  def show
    @post = Post.find(params[:id])
    # @post.visited
    # @comments = @post.comments.order(created_at: :desc)
    # respond_to do |format|
    #   format.html
    #  end

  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  layout false

  def create
    unless request.xhr?
      logger.warn "attack action detected: #{params.to_h}"
      redirect_to root_path
      return
    end
    cookies[:name] = comment_params[:name]
    cookies[:email] = comment_params[:email]
    @post = Post.find(params[:blog_id])
    @comment = @post.comments.build(comment_params)

    if @comment.save
      @comments = @post.comments.order(created_at: :desc)
      flash[:notice] = 'you created a comment'
      respond_to do |format|
        format.html {redirect_to blog_path(@post)}
        format.js
      end
    end
   end

  private
  def comment_params
    params.require(:comment).permit(:content, :name, :email)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/admin/comments/index.html.erb
<div class="row">
    <div class="col-lg-12">
        <h3>Comment Management</h3>
        <h4>Post title: <%= link_to @post.title, blog_path(@post), target: "_blank" %></h4>
        <table class="table table-hover">
            <tr>
                <th>name</th>
                <th>email</th>
                <th>content</th>
                <th>date</th>
                <th>operation</th>
            </tr>
            <% @comments.each do |comment| %>
            <tr>
                <td><%= comment.name %></td>
                <td><%= comment.email %></td>
                <td><%= simple_format(comment.content) %></td>
                <td><%= format_time(comment.created_at) %></td>
                <td>
                    <%= link_to 'Reply', blog_path(@post),target: '_blank' %>
                </td>
                <td>
                    <%= link_to 'Delete', admin_post_comment_path(@post, comment), method: 'Delete', 'data-confirm'=> 'Are you sure to delete?' %>
                </td>
            </tr>
            <% end -%>
        </table>
    </div>
</div>

app/views/admin/dashboard/index.html.erb
<div class="container">
  <h2>Blog stats</h2>
  <table class="table table-hover">
    <thead>
      <tr>
        <th>INFO</th>
         <th>STATES</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td>Post</td>
         <td><%= @posts_count %></td>
      </tr>
      <tr>
        <td>Mary</td>
         <!-- <td><%= @visited_count %></td> -->
      </tr>
      <tr>
        <td>Comment</td>
         <td><%= @comments_count %></td>
      </tr>
    </tbody>
  </table>
</div>

app/views/admin/posts/index.html.erb
<table class="table table-hover">
  <tr>
    <th>标题</th>
    <th>概要</th>
    <th>操作</th>
  </tr>
  <% @posts.each do |post| %>
    <tr>
      <td><%=  link_to post.title, blog_path(post), target: '_blank' %>
      <% post.tags.each do |tag| %>
        <span class="badge"><%= tag.title %></span>
      <% end %>
      </td>
      <td><%= format_date(post.created_at) %></td>

      <td>
        <%= link_to "comments", admin_post_comments_path(post.id) %>
      </td>
      <td>
        <%= link_to "edit", edit_admin_post_path(post) %>
      </td>
      <td>
        <%= link_to "delete", admin_post_path(post), method: 'DELETE', 'data-confirm'=>'are you sure to delete?'%>
      </td>
    </tr>
  <% end -%>
</table>

<%= paginate @posts %>

app/views/admin/posts/new.html.erb
<h1><%= @post.new_record? ? 'Create' : 'Edit' %>  Blog</h1>
<div class="row">
    <div class="col-md-8">
        <%= form_for [:admin, @post]  do |f| %>
        <div class="form-group">
            <ul class="list-unstyled">
                <% @post.errors.messages.values.flatten.each do |error| %>
                  <li>
                    <i class="fa fa-exclamation-circle"></i>
                    <%= error %>
                  </li>
                <% end -%>
            </ul>
        </div>

        <div class="form-group">
            <%= f.text_field :title, class: "form-control", placeholder: "标题" %>
        </div>

         <ul class="nav nav-tabs" id="myTab">
                <li class='active'>
                    <a id='content_tab' >content</a>
                </li>
                <li>
                    <a id='preview_tab'>preview</a>
                </li>
          </ul>

          <div class="tab-content">
                <div id="content-field" class="tab-pane active">
                    <p>
                        <%= f.text_area :content, class: "form-control", rows: "15", placeholder: "内容" %>
                    </p>
               </div>
              <div id="preview-field" class="tab-pane">123</div>
         </div>

        <div class="form-group">
          <input type="text" name="tags" value="<%= @post.tags.map(&:title).join(',') %>"> <small>tags 以逗号隔开</small>
        </div>

        <%= f.submit "保存", class: "btn btn-primary" %>
        <% end -%>
  </div>

</div>

app/views/blogs/_comment.html.erb
<div class="row">
    <div class="col-lg-8">
        <div class="well">
            <h4>Leave your comments</h4>
            <%= form_for Comment.new, url: blog_comments_path(@post), class: 'new_comment', remote: true do |f| %>
            <div class="form-group" id="comment_content">
                <%= f.text_area :content, rows: 5, class: 'form-control', placeholder: 'write a comment..' %>
            </div>
            <div class="form-group" id="comment_name">
                <%= f.text_field :name , value: cookies[:name], class: 'form-control' , placeholder: 'your name..'%>
            </div>
            <div class="form-group" id="comment_email">
                <%= f.text_field :email , value:cookies[:email], class: 'form-control', placeholder: 'your email...'%>
            </div>
            <%= f.submit 'Post Comment', class: 'button' %>
            <% end %>
        </div>
        <hr>
        <%= render partial: "comments/comment_content", locals: { comments: comments, post: @post}%>
    </div>
</div>

app/views/blogs/_likes.html.erb
<% if Cookies.likes?(blog) %>
<%= link_to "unlike", url: blog_like_path(blog), method: :delete, remote: true %>
<% else %>
<%= link_to "like", url: blog_like_path(blog), method: :post, remote: true %>
<% end %>
<%= blog.likes.count %>

app/views/blogs/_search.html.erb
<div class="col-md-4">

   <!-- Blog Search Well -->
   <div class="well">
       <h4>Blog Search</h4>
       <div class="input-group">
         <%= search_form_for @q, url: blogs_path do |f| %>
         <%= f.search_field :title_or_content_cont %>
         <%= f.submit %>
        <% end %>
       </div>
    </div>


    <div class="well">
        <h4>Latest Posts</h4>
        <% latst_posts.each do |post| %>
        <ul>
          <li><%= link_to post.title, blog_path(post) %></li>
        </ul>
        <% end %>
    </div>
</div>

app/views/blogs/index.html.erb
<div class="row">

     <div class="col-md-8">

        <% @posts.each do |post| %>

        <h2>
            <%= post.title %>
        </h2>

        <p>
          <% post.tags.each do |tag| %>
            <span class="badge"><%= tag.title %></span>
          <% end %>
        </p>

        <p>
            <span class="glyphicon glyphicon-time"></span>
            Posted on <%= format_date(post.created_at) %>
        </p>
        <hr>
        <%= truncate( strip_tags( MyMarkdown.to_md(post.content) ), length: 150)  %>
        <br>
        <br>

        <%= link_to "Read More " , blog_path(post), class: "btn btn-primary"%>
        <br>
        <br>
        <br>

        <% end %>

        <ul class="pager">
            <li class="paginate">
                <%= paginate @posts %>
            </li>
        </ul>
    </div>
    <%= render partial: "search" , locals: {latst_posts: @latst_posts} %>
</div>

app/views/blogs/likes/create.js.erb
($"#likes").html("<%= j render partial: 'blogs/likes' , locals: {blog: @blog} %>");

app/views/blogs/likes/destroy.js.erb
($"#likes").html("<%= j render partial: 'blogs/likes', locals: {blog: @blog} %>");

app/views/blogs/show.html.erb
<div class="container">
    <div class="row">
       <div class="col-lg-8">
           <h1><%= @post.title %></h1>
           <p>
             <% @post.tags.each do |tag| %>
               <span class="badge"><%= tag.title %></span>
             <% end %>
           </p>
           <p><span class="glyphicon glyphicon-time"></span> Posted on <%= format_date(@post.created_at) %></p>
           <hr>
           <p>
              <%= MyMarkdown.to_md(@post.content) %>
          </p>
          <div id="likes">
            <%= render partial: "likes", locals: {blog: @blog} %>
          </div>
          <br>
          <hr>
          <br>
        <div class="comment-field">
          <%= render partial: "comment", locals: {comments: @comments, post: @post} %>
        </div>
      </div>
    </div>
</div>

app/views/comments/_comment_content.html.erb
<div class="comment-diag">
    <% @post.comments.each do |comment| %>
    <div class="comment-wrapper">
        <span class="glyphicon glyphicon-user"></span>
        <%= comment.name %>
        <small>
            <span class="glyphicon glyphicon-time"></span>
            <%= format_time(comment.created_at) %></small>
    </div>
    <div class="comment-content">
        <%= comment.content %>
    </div>
    <br>
    <% end %>
</div>

app/views/comments/create.js.erb
$('#comment_content').val('');
$('.comment-diag').replaceWith('<%= j render partial: 'comment_content', locals: {comments: @comments} %>');

app/views/layouts/_footer.html.erb
<!-- Footer -->
<footer>
    <div class="row">
        <div class="col-lg-12">
            <p>Copyright &copy; shenzhenlist.com 2016  （粤ICP备16099064号-1 ）
              Supported by  <a href="https://www.upyun.com/index.html"><img src="https://www.upyun.com/assets/league/90X45.png"></a>
            </p>
        </div>
        <!-- /.col-lg-12 -->
    </div>
    <!-- /.row -->
</footer>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
    <head>
        <title>Admin SZblog</title>
        <%= csrf_meta_tags %>
        <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0">
        <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
        <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    </head>

    <body>

        <!-- Navigation -->
        <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
            <div class="container">
                <!-- Brand and toggle get grouped for better mobile display -->
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <%= link_to "Admin", admin_dashboard_index_path, class: "navbar-brand" %>

                </div>
                <!-- Collect the nav links, forms, and other content for toggling -->
                <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                    <ul class="nav navbar-nav">
                        <li>
                            <%= link_to "Blogs", admin_posts_path %>
                        </li>
                        <li>
                            <%= link_to "Create Blog", new_admin_post_path %>
                        </li>

                    </ul>
                    <ul class="nav navbar-nav navbar-right">
                        <li>
                            <%= link_to "home", blogs_path, target: "_blank" %>
                        </li>
                        <li>
                            <% if admin_username %>
                            <li><%= link_to "#{admin_username} ,logout", admin_session_path(1), method: 'delete'%></li>
                            <% end %>
                       </li>
                  </ul>
             </div>
            <!-- /.navbar-collapse -->
          </div>
          <!-- /.container -->
      </nav>

      <!-- Page Content -->
      <div class="container">

          <% if flash[:notice] %>
          <div class="alert alert-info">
              <%= flash[:notice] %>
          </div>
          <% end %>

          <%= yield %>

          <%= render 'layouts/footer' %>

      </div>
      <!-- /.container -->

    </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
    <head>
        <title>Szblog</title>
        <%= csrf_meta_tags %>
        <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0">
        <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
        <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    </head>

    <body>

        <!-- Navigation -->
        <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
            <div class="container">
                <!-- Brand and toggle get grouped for better mobile display -->
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <%= link_to "SZ blog", blogs_path, class: "navbar-brand" %>
                </div>
                <!-- Collect the nav links, forms, and other content for toggling -->
                <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                    <ul class="nav navbar-nav">
                        <li>
                            <a href="#">About</a>
                        </li>
                        <li>
                            <%= link_to 'Blog', blogs_path %>
                        </li>

                    </ul>
                    <ul class="nav navbar-nav navbar-right">
                        <li>
                            <%= link_to 'login', new_admin_session_path %>
                        </li>
                    </ul>
                </div>
                <!-- /.navbar-collapse -->
            </div>
            <!-- /.container -->
        </nav>

        <!-- Page Content -->
        <div class="container">
            <% if flash[:notice] %>
            <div class="alert alert-info">
                <%= flash[:notice] %>
            </div>
            <% end %>

            <%= yield %>

            <%= render 'layouts/footer' %>
        </div>
        <!-- /.container -->

    </body>
</html>

app/views/welcome/index.html.erb
<h1>Welcome#index</h1>
<p>Find me in app/views/welcome/index.html.erb</p>